version: '3.3'
services:
  #db:
  #  image: mysql:5.7
  #  volumes:
  #    - /opt/test:/var/lib/mysql
  #    - ./mysql-dump:/docker-entrypoint-initdb.d
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: testdb1
  #    MYSQL_USER: admin
  #    MYSQL_PASSWORD: admin
  #  ports:
  #    - 3306:3306
  #phpmyadmin:
    #depends_on:
    #  - db
    #image: phpmyadmin/phpmyadmin
    #ports:
    #  - '8081:80'
    #environment:
    #  PMA_HOST: db
    #  MYSQL_ROOT_PASSWORD: root
  web:
    #depends_on
    #  - db
    image: tomcat
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8080:8080'
    #environment:
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: testdb1
      #MYSQL_USER: admin
      #MYSQL_PASSWORD: admin