version: '3.3'
services:
  link-checker-web-service:
    container_name: link-checker-web-service
    build:
      context: link-checker-web-service
      dockerfile: Dockerfile
    image: link-checker-web-service:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge